# Generated by Django 6.0 on 2025-12-31 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BBapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
            ],
        ),
    ]
